#!/bin/bash
# reference https://github.com/yyuu/pyenv/wiki/Common-build-problems
sudo apt-get install -y \
make wget curl llvm \
libssl-dev \
zlib1g-dev \
libbz2-dev \
libsqlite3-dev \
libreadline-dev \
build-essential \
libncurses5-dev \
libncursesw5-dev \
xz-utils

curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash

if ! [ -d ~/bashrc.d ]; then
  ../bash/setup.sh
fi

cp ../bash/bashrc.d/pyenv.bashrc ~/bashrc.d/