alias addppa='sudo add-apt-repository -y'
alias cls='clear'
alias optim.jpg='jpegoptim *.jpg *.jpeg'
alias optim.png='optipng *.png'
alias py2='python2'
alias py3='python3'
alias unzip.big5='unzip -O cp950'
alias unzip.gb='unzip -O cp936'
alias unzip.jp='unzip -O cp932'
alias unzip.kr='unzip -O cp949'
alias wine.jp='LANG=ja_JP.utf8 wine'
